In [8]:
import pandas as pd
from loader import *
import matplotlib.pyplot as plt
import jieba
import jieba.analyse



In [25]:
def question_semantic(query):
    context = ['沒有', '錯誤', '不正確', '不是', '有誤', '不曾', '不包含', '測不到']
    label = []
    for q in query:
        for v in context:
            if(q.find(v)!=-1):
                label.append(0)
                break
            elif v==context[-1]: 
                label.append(1)
    return label


In [17]:
doc, q, cho, ans = json_parser()

In [26]:
q_label = question_semantic(q)

In [27]:
list(zip(q, q_label))

[('下列關於民眾的敘述，何者有誤？', 0),
 ('下列關於民眾敘述何者錯誤?', 0),
 ('關於民眾戴套的觀念，何者有誤?', 0),
 ('下列關於民眾敘述，何者錯誤？', 0),
 ('下列敘述何者錯誤？', 0),
 ('關於民眾的敘述，何者錯誤？', 0),
 ('下列敘述何者錯誤？', 0),
 ('關於民眾的性生活下列何者正確？', 1),
 ('下列何者不是民眾保護自己的方式？', 0),
 ('下列敘述何者有誤?', 0),
 ('請問下列何者不是醫師建議民眾性行為時保護自己的方式？', 0),
 ('下列何者是民眾目前PrEP的吃法？', 1),
 ('請問HIV對生活上面沒有什麼影響？', 0),
 ('下列何者是PrEP可以預防的性傳染病？', 1),
 ('關於民眾這個月性生活的敘述下列何者錯誤？', 0),
 ('請問下列何者不是個管師建議民眾性行為時的預防方式？', 0),
 ('請問如果連續吃藥的話，要吃幾天才會有保護效力？', 1),
 ('關於民眾的敘述何者有誤?', 0),
 ('下列選項何者正確?', 1),
 ('民眾得梅毒是因為下列何者原因？', 1),
 ('關於民眾目前的性生活下列何者正確？', 1),
 ('請問民眾一次吃兩顆藥會有何種反應？', 1),
 ('下列何者不是民眾這個月性行為的狀況？', 0),
 ('下列何者是PrEP可以預防的疾病？', 1),
 ('請問關於PrEP的敘述，下列何者是錯誤的？', 0),
 ('下列何者不是肉眼看得到的性傳染疾病？', 0),
 ('民眾目前的情況下列何者正確？', 1),
 ('對於PrEP的敘述下列何者正確？', 1),
 ('請問醫師建議民眾第一個月要如何吃藥？', 1),
 ('下列何者是民眾這次抽血要驗的指數？', 1),
 ('關於民眾的敘述，何者有誤？', 0),
 ('請問民眾決定要買何種藥？', 1),
 ('下列何者不是任務型的吃法？', 0),
 ('請問PrEP只能預防哪種疾病？', 1),
 ('民眾性經驗敘述下列何者正確？', 1),
 ('關於民眾的敘述何者錯誤?', 0),
 ('下列敘述何者有誤?', 0),
 ('關於病毒敘述下列何者錯誤？', 0),
 ('關於Prep吃法下列何者錯誤？', 0),
 ('民眾從任務型改

In [ ]:
doc[0]

In [ ]:
frag_len = [ len(frag) for frag_doc in doc for frag in frag_doc]
max(frag_len), min(frag_len)

In [ ]:
plt.title('Fragment len')
plt.hist(frag_len)
plt.show()

In [ ]:
allfragment_len = [sum([len(e) for e in ele]) for ele in doc]
plt.hist(allfragment_len)
plt.show()


In [ ]:
def cat_sents(idx, end):
    indices = [idx]
    head = tail = idx
    dir = 0
    while len(indices) != 16:
        print(head, tail)
        if tail+1< end and dir==0: 
            tail+=1
            indices.append(tail)
        elif head-1>=0 and dir==1:
            head-=1   
            indices.append(head)
        dir=not dir
    return indices

In [ ]:
cat_sents(48, 50)

In [ ]:
import difflib

In [ ]:
difflib.SequenceMatcher(None, '123', '56161').quick_ratio()

In [ ]:
import numpy as np
a = np.array([
    [3, 40, 20,],
    [1, 56, 21],
    [441, 560, 28],
    [11, 5, 2],
])


In [ ]:
ind = np.argpartition(a, -3, axis=0)[-3:]
ind


In [ ]:
ind[:, 0]

In [ ]:
ind[np.argsort(a[ind])]


In [ ]:
import torch 

In [ ]:
a = torch.rand((1,2,3))
b = torch.rand((1,3,3))
a,b

In [ ]:
torch.cat((a, b), dim=1)

In [ ]:
with open('./data/stop_word.txt') as f:
    text = f.read()
    text = text.split('\n')

In [ ]:
[1,2] + [2,3]

In [ ]:
tags = jieba.analyse.extract_tags('醫師：我們6月30號抽血，免疫細胞指數還不錯這樣子，然後病毒量也是OK，阿血糖，糖化血色素7.2，還不錯，所以控制的還不錯，所以表示這段時間身體狀況應該還好。民眾：因為我有重訓和訓練……醫師：低密度膽固醇101是正常，是可以的，然後因為有一點點尿酸稍微高一點點，但是還不需要吃藥，就是飲食稍微注意一下就好，會造成尿酸高一點的食物稍微控制一下就好。民眾：我不知道哪些。醫師：不')
tags

In [ ]:
import spacy
from spacy.lang.zh import Chinese
from spacy.language import Language

text = '醫師：我們6月30號抽血，免疫細胞指數還不錯這樣子，然後病毒量也是OK，阿血糖，糖化血色素7.2，還不錯，所以控制的還不錯，所以表示這段時間身體狀況應該還好。民眾：因為我有重訓和訓練……醫師：低密度膽固醇101是正常，是可以的，然後因為有一點點尿酸稍微高一點點，但是還不需要吃藥，就是飲食稍微注意一下就好，會造成尿酸高一點的食物稍微控制一下就好。民眾：我不知道哪些。醫師：不。'

In [ ]:
@Language.component("set_custom_boundaries")
def set_custom_boundaries(doc):
    
    position = ['民眾', '個管師', '醫師', '女醫師', '護理師', '家屬', '藥師', ]
    position = [ role+'：' for role in position] + \
                [ role + ele + '：' for role in position for ele in ['A', 'B', '1', '2']]

    for token in doc[:-1]:
#         print(token, token.i)
        if token.text in position:
            doc[token.i].is_sent_start = True
        elif token.i>0 and doc[token.i-1].text in ['，', '？', '。', ]:
            doc[token.i].is_sent_start = True
        else:
            doc[token.i].is_sent_start = False
    return doc
nlp = spacy.load("zh_core_web_sm")
nlp = Chinese()
nlp = Chinese.from_config({"nlp": {"tokenizer":{"segmenter": "pkuseg"}}})
nlp.tokenizer.initialize(pkuseg_model="mixed", pkuseg_user_dict='./data/pkuseg_user_dict.txt')
nlp.add_pipe("sentencizer")
nlp.add_pipe("set_custom_boundaries")
doc = nlp(text)


In [ ]:
[sen.text for sen in doc.sents]

In [ ]:
a = torch.tensor([
    [
        [1,2,3],
        [0,0,0],
        [3,4,3]
    ],
    [
        [1,2,3],
        [1,2,3],
        [3,4,3]
    ],
], dtype=torch.float)
b = torch.tensor([
    [
        [1,2,3],
        [3,4,3]
    ],
    [
        [1,2,3],
        [3,4,3]
    ],
], dtype=torch.float)
cosine_sim()(a, b)

In [ ]:
cosine_sim()(a, b)

In [ ]:
torch.max(cosine_sim()(a, b), 1)

In [ ]:
# output = torch.randn(2, 4, 768)
# choi_output = torch.randn(2, 3, 768)
cosine_sim(None)(a, b)

In [ ]:
vec1=a
vec2=b

vec2 = torch.transpose(vec2, 1, 2)
norm1 = torch.linalg.norm(vec1, dim=2)
norm2 = torch.linalg.norm(vec2, dim=1)   
norm1 = norm1.unsqueeze(-1).expand(2, vec1.size(1), vec1.size(2))
norm2 = norm2.unsqueeze(2).expand(2, vec2.size(2), vec2.size(1))
norm2 = torch.transpose(norm2, 1, 2)
eledot = torch.matmul(torch.div(vec1, norm1), torch.div(vec2, norm2))

# print(torch.mul(norm1.transpose(0, 1), norm2))
# cos_sim = torch.div(eledot ,torch.matmul(norm1.transpose(0, 1), norm2))
eledot

In [ ]:
norm2 = norm2.unsqueeze(2).expand(2, vec2.size(2), vec2.size(1))
norm2 = torch.transpose(norm2, 1, 2)

In [ ]:
' rock '

In [ ]:
from loader import QA_Dataset
from transformers import AutoTokenizer
config = 'hfl/chinese-xlnet-base'
tokenizer = AutoTokenizer.from_pretrained(config)


In [ ]:
example = QA_Dataset(tokenizer, './data/train_fold1.json').__getitem__(1)
example['input_ids'].shape 

In [ ]:
tokenizer.decode(example['input_ids'][0][0])

In [ ]:
tokenizer.decode(ins['q_input_ids'][0])

In [ ]:
import pandas as pd
from loader import *
import matplotlib.pyplot as plt
from transformers import AutoTokenizer


config = 'hfl/chinese-xlnet-base'
tokenizer = AutoTokenizer.from_pretrained(config)
doc, q, cho, ans = json_parser()

In [ ]:
import jieba
jieba.load_userdict('./data/dict.txt') 
# lijieba.lcut(text))

In [ ]:
def find_entity(strs, ent, dir='f'):
    try:
        idx = strs.index(ent)
        idx = idx-1 if dir=='f' else idx+1
        return strs[idx]
    except:
        return 0
def query_propress(query):
    valid_ent = ['民眾', '醫師', '個管師', '家屬']
    rules=[ 
        {'p':'關於','dir':'b'}, {'p':'建議','dir':'f'},
        {'p':'是', 'dir':'b'}, {'p':'不是', 'dir':'b'},
        {'p':'請問', 'dir':'b'}
    ]
    processed_q = []
    for q in query:
        tokens = jieba.lcut(q)
        # print(tokens)
        res = ''
        for ele in rules:
            res = find_entity(tokens, ele['p'], dir=ele['dir'])  

            if res in valid_ent: break
        # Clearing invalid ent
        if not res in valid_ent:
            res= tokens[0] if tokens[0] in valid_ent else ''
            
        processed_q.append(res)
    return processed_q


In [ ]:
propressed_query = query_propress(q)
list(zip(q, propressed_query))

In [ ]:
pipe =  doc_preprocessing(config)
d = pipe(doc, q)

# ori_len = [len(window) for frag in d for window in frag['input_ids']]
# plt.hist(ori_len, color = 'black', cumulative = False)
# plt.show()

In [ ]:
tokenizer.decode(d[0]['q_input_ids'][0])

In [ ]:
plt.hist(strQ2B(ans))
plt.show()


## LOADER

In [ ]:
from torch.utils.data import DataLoader
from loader import QA_Dataset
from torch.nn.utils.rnn import pad_sequence
import torch

config = 'hfl/chinese-xlnet-base'
lr = 1e-3

In [ ]:
import  torch.nn.functional as F
from torch.nn.utils.rnn import pad_sequence
a = torch.ones(25, 300)
b = torch.ones(22, 300)
c = torch.ones(15, 300)
pad_sequence([a, b, c], batch_first=True,).shape

In [ ]:
def fragment_pad(*dcts):
    combined_dict = {}
    for k in set(dcts[0]):
        if not k=='label' and not k=='choice':
            print(k, [d[k].shape for d in dcts])
            combined_dict.update({
                k:pad_sequence([d[k].squeeze(0) for d in dcts], batch_first=True)
            })
        if k=='label':
             combined_dict.update({
                'label':torch.stack([d['label'] for d in dcts]) 
             })
    return combined_dict

def collate_fn(batch):
    batched_dict = fragment_pad(*batch)
    return batched_dict

train_ds = QA_Dataset(config, './data/Train_qa_ans.json')
train_loader = DataLoader(
    train_ds, 
    batch_size=4, 
    num_workers=1, 
    shuffle=True, 
    collate_fn=collate_fn
)
train_loader.__iter__().__next__()
# model = QA_Model(config, lr=lr)

In [ ]:
from loader import QA_Dataset

In [ ]:
from transformers import XLNetTokenizer, XLNetModel
import torch

config = 'hfl/chinese-xlnet-base'
tokenizer = XLNetTokenizer.from_pretrained(config)
tokenizer.add_special_tokens({'additional_special_tokens':['<q>']})
model = XLNetModel.from_pretrained(config)
model.resize_token_embeddings(len(tokenizer))

In [ ]:
tokenizer([
    ('預計的性行為', '預計的性行為'),
    ('預預預預預預', '預預預預預預'),

])['input_ids'][0]

In [ ]:
tokenizer.decode(19)

In [ ]:
c ='預計的性行為，前面兩個小時吃兩顆，24小時後，再吃一顆，再一個24小時之後吃一顆'

ids = tokenizer([c, c[0:30]], max_length=40, padding='max_length').input_ids
tokenizer.decode(ids[0])

In [ ]:
for ele in ids[0]:
    print(    tokenizer.decode(ele))


In [ ]:
tokenizer.decode(ids[1])

## Model

In [ ]:
h = model(**encoding).last_hidden_state

In [ ]:
from transformers.modeling_utils import SequenceSummary


In [ ]:
s = SequenceSummary(config)
getattr(config, 'summary_type', 'last')

In [ ]:
t = torch.empty(3).random_(5)
mask = torch.empty(3).random_(2)
t, mask

In [ ]:
t * mask

In [2]:
import torch
from torch import nn
import math 
import torch.nn.functional as F

def mask_logits(target, mask):
    return target * (1-mask) + mask * (-1e30)

In [6]:
s = torch.rand((2,2,4))
mask = torch.empty((2,2,1)).random_(2)
s, mask


(tensor([[[0.5552, 0.2233, 0.5149, 0.5096],
          [0.3805, 0.0324, 0.6696, 0.6755]],
 
         [[0.3808, 0.3513, 0.4739, 0.1725],
          [0.3329, 0.6166, 0.6477, 0.8960]]]),
 tensor([[[1.],
          [0.]],
 
         [[0.],
          [0.]]]))

In [7]:
mask.repeat(1,3,1)

tensor([[[1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]])

In [5]:
torch.max(s, dim=2)

torch.return_types.max(
values=tensor([[0.7636, 0.8726],
        [0.8092, 0.9350]]),
indices=tensor([[2, 1],
        [2, 2]]))

In [65]:
mask_logits(s, mask)

tensor([[[ 8.3742e-01,  9.0270e-01,  6.4777e-01,  2.3296e-01],
         [ 4.0762e-01,  1.6231e-01,  9.4158e-01,  8.8146e-01]],

        [[-1.0000e+30, -1.0000e+30, -1.0000e+30, -1.0000e+30],
         [-1.0000e+30, -1.0000e+30, -1.0000e+30, -1.0000e+30]]])

In [ ]:
d_model = 768
class CQAttention(nn.Module):
    def __init__(self):
        super().__init__()
        w = torch.empty(d_model * 3)
        lim = 1 / d_model
        nn.init.uniform_(w, -math.sqrt(lim), math.sqrt(lim))
        self.w = nn.Parameter(w)

    def forward(self, C, Q, cmask, qmask):
        C = C.transpose(1, 2)
        Q = Q.transpose(1, 2)
        cmask = cmask.unsqueeze(2)
        qmask = qmask.unsqueeze(1)
        
        shape = (C.size(0), C.size(1), Q.size(1), C.size(2))
        print(shape)
        Ct = C.unsqueeze(2).expand(shape)
        Qt = Q.unsqueeze(1).expand(shape)
        CQ = torch.mul(Ct, Qt) 
        S = torch.cat([Ct, Qt, CQ], dim=3)
        S = torch.matmul(S, self.w)
        S1 = F.softmax(mask_logits(S, qmask), dim=2)
        S2 = F.softmax(mask_logits(S, cmask), dim=1)
        A = torch.bmm(S1, Q)
        B = torch.bmm(torch.bmm(S1, S2.transpose(1, 2)), C)
        out = torch.cat([C, A, torch.mul(C, A), torch.mul(C, B)], dim=2)
        out = F.dropout(out, p=dropout, training=self.training)
        return out.transpose(1, 2)

In [ ]:
context = torch.randn((2,50,768))
query = torch.randn((2,30,768))
cmask = (torch.empty((2, 50)).random_(2) == 0).float()
qmask = (torch.empty((2, 30)).random_(2) == 0).float()

att = CQAttention()


In [ ]:
v = att(context, query, cmask, qmask)
v.shape

In [1]:
a = torch.empty(1,1,5).random_(2)
b = torch.empty(1,3,5).random_(2)
a,b

NameError: name 'torch' is not defined

In [38]:
a * b

tensor([[[0., 1., 1., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.]]])

In [33]:
(context * query.select(1, 2).unsqueeze(1)).shape

torch.Size([2, 50, 768])

In [31]:
query.select(1, 2).unsqueeze(1).shape

torch.Size([2, 1, 768])

In [49]:
class att_flow_layer(nn.Module):
    """
    :param c: (batch, c_len, hidden_size * 2)
    :param q: (batch, q_len, hidden_size * 2)
    :return: (batch, c_len, q_len)
    """
    def __init__(self,):
        super(att_flow_layer, self).__init__()
        self.att_weight_c = nn.Linear(768, 1)
        self.att_weight_q = nn.Linear(768, 1)
        self.att_weight_cq = nn.Linear(768, 1)

    def forward(self, c, q):
        c_len = c.size(1)
        q_len = q.size(1)

        cq = []
        for i in range(q_len):
            #(batch, 1, hidden_size * 2)
            qi = q.select(1, i).unsqueeze(1)
            #(batch, c_len, 1)
            ci = self.att_weight_cq(c * qi).squeeze()
            cq.append(ci)
        # (batch, c_len, q_len)
        cq = torch.stack(cq, dim=-1)
        # (batch, c_len, q_len)
        s = self.att_weight_c(c).expand(-1, -1, q_len) + \
            self.att_weight_q(q).permute(0, 2, 1).expand(-1, c_len, -1) + \
            cq
        # (batch, c_len, q_len)
        a = F.softmax(s, dim=2)
        # (batch, c_len, q_len) * (batch, q_len, hidden_size * 2) -> (batch, c_len, hidden_size * 2)
        c2q_att = torch.bmm(a, q)
        # (batch, 1, c_len)
        b = F.softmax(torch.max(s, dim=2)[0], dim=1).unsqueeze(1)
        # (batch, 1, c_len) * (batch, c_len, hidden_size * 2) -> (batch, hidden_size * 2)
        q2c_att = torch.bmm(b, c).squeeze()
        # (batch, c_len, hidden_size * 2) (tiled)
        q2c_att = q2c_att.unsqueeze(1).expand(-1, c_len, -1)
        # q2c_att = torch.stack([q2c_att] * c_len, dim=1)
        # (batch, c_len, hidden_size * 8)
        x = torch.cat([c, c2q_att, c * c2q_att, c * q2c_att], dim=-1)
        return x

In [51]:
att_flow_layer()(context, query).shape

torch.Size([2, 50, 3072])