In [1]:
import pandas as pd
from loader import *
import matplotlib.pyplot as plt
import jieba
import jieba.analyse
import  pkuseg



In [12]:
ws=pkuseg.pkuseg(user_dict='./data/dict.txt' ).cut
jieba.load_userdict('./data/dict.txt') 
ws=jieba.lcut

In [9]:
ws('那你的line是ＰＲＥＰ這個嗎')

['那', '你', '的', 'line', '是', 'Ｐ', 'Ｒ', 'Ｅ', 'Ｐ', '這個', '嗎']

In [25]:
def full2half(s):
    n = []
    # s = s.decode('utf-8')
    for char in s:
        num = ord(char)
        if num == 0x3000:
            num = chr(num)
        elif 0xFF01 <= num <= 0xFF5E:
            num -= 0xfee0
            num = chr(num)
        else: num=char
        n.append(num)
        # print(n)
    return ''.join(n)


In [38]:
full2half('那你的line是ＰＲＥＰ這個嗎：::，，。。.......⋯⋯⋯⋯……８７')

'那你的line是PREP這個嗎:::,,。。.......⋯⋯⋯⋯……87'

In [13]:
doc, q, cho, ans = json_parser()

def tokenize(ins):
    
    role_ins = []
    ins_frag = []
    for frag in ins:
        roleid = []
        tokenize_sen = []
        sents = frag.split('<')[1:]
        for s in sents:
            try:
                sid = int(s[0])
            except:
                print(s)

            # print(s[3:], '\n')
            s = ws(s[2:])
            # print(s)
            roleid += [sid] * len(s)
            tokenize_sen+=s

        role_ins.append(roleid)
        ins_frag.append(tokenize_sen)
        assert len(roleid) == len(tokenize_sen)
    return {
        'raw_text': ins_frag,
        'roleid' :role_ins,
    }

In [14]:
i = 1
doc[i], q[i], cho[i], ans[i]

(['<1>嗯～<2>就會下降這樣子，<2>那膽固醇的話是141。<1>嗯。<2>200以下是正常。<1>哦～<2>高密度膽固醇54，<2>這個是好的膽固醇。<1>對。<2>這個要在40以上，<2>所以吳老師部分ＯＫ。<1>所以其實這個是高一點也沒關係。<2>對這個是好的。<1>好的嘛。<2>他會有保護的效果。<1>這個是總和嘛齁？<2>這個是總和對，<2>啊這個是低密度膽固醇，<2>低密度膽固醇就是會卡在心血管上面會造成。<1>啊這樣子算有點偏高嗎？<2>嘿正常。<1>正常喔。<1>那樣的習慣的人才有。<2>ＯＫ啊。<1>就是偏高就對了齁？<2>啊尿液的部分呢是，<2>我看一下，<2>ＰＨ值是正常，<2>沒有蛋那個，<2>沒有尿糖，<2>然後呢蛋白尿我們也有測，<2>ＰＲＯＴＥＩＮ，<2>在這裡齁，',
  '<1>嗯～<2>就會下降這樣子，<2>那膽固醇的話是141。<1>嗯。<2>200以下是正常。<1>哦～<2>高密度膽固醇54，<2>這個是好的膽固醇。<1>對。<2>這個要在40以上，<2>所以吳老師部分ＯＫ。<1>所以其實這個是高一點也沒關係。<2>對這個是好的。<1>好的嘛。<2>他會有保護的效果。<1>這個是總和嘛齁？<2>這個是總和對，<2>啊這個是低密度膽固醇，<2>低密度膽固醇就是會卡在心血管上面會造成。<1>啊這樣子算有點偏高嗎？<2>嘿正常。<1>正常喔。<1>那樣的習慣的人才有。<2>ＯＫ啊。<1>就是偏高就對了齁？<2>啊尿液的部分呢是，<2>我看一下，<2>ＰＨ值是正常，<2>沒有蛋那個，<2>沒有尿糖，<2>然後呢蛋白尿我們也有測，<2>ＰＲＯＴＥＩＮ，<2>在這裡齁，',
  '<1>嗯～<2>就會下降這樣子，<2>那膽固醇的話是141。<1>嗯。<2>200以下是正常。<1>哦～<2>高密度膽固醇54，<2>這個是好的膽固醇。<1>對。<2>這個要在40以上，<2>所以吳老師部分ＯＫ。<1>所以其實這個是高一點也沒關係。<2>對這個是好的。<1>好的嘛。<2>他會有保護的效果。<1>這個是總和嘛齁？<2>這個是總和對，<2>啊這個是低密度膽固醇，<2>低密度膽固醇就是會卡在心血管上面會造成。<1>啊這樣子算有點偏高嗎？<2>嘿正常。<1>正常喔。<1>那樣的習慣的人才有。<2>ＯＫ啊。<1>就是偏高就對了齁？<2>啊尿液的部分呢

In [35]:
len(tokenize(doc[166])['raw_text'][1])

154

In [37]:
a= torch.randn((2,3,12))
ab

tensor([[[-6.6831e-02, -5.2485e-01,  6.1045e-01, -7.6859e-02,  4.9431e-01,
           1.8986e-01, -1.8368e+00, -1.3222e+00,  8.7111e-01,  4.3258e-01,
          -3.2533e-01,  8.9563e-01],
         [ 7.7752e-04,  1.3285e+00, -7.5241e-02, -1.2557e-02,  8.4139e-01,
           3.9887e-04,  2.2646e-01, -7.8450e-01,  5.8338e-01, -1.7438e+00,
           1.2119e+00,  1.0964e+00],
         [-2.2583e-01, -1.7354e+00,  1.8012e+00, -4.0434e-01,  1.1555e+00,
          -4.7239e-02, -1.6321e+00,  7.4819e-01, -1.5800e+00,  8.3304e-02,
           1.2905e+00, -1.9404e-01]],

        [[-1.5224e-01,  2.2067e+00,  7.8872e-01,  1.2492e+00,  3.4109e-02,
           2.4306e-01,  1.0006e+00,  8.8748e-02, -4.5431e-01,  1.0941e+00,
           1.8342e+00, -2.0721e-01],
         [-2.3212e-01,  8.2180e-02,  5.4369e-01, -3.0683e-01,  8.9243e-02,
          -4.4669e-01,  4.6182e-01,  1.6795e+00,  1.8753e+00,  2.3479e-02,
           5.6987e-01,  1.1448e-01],
         [ 8.6930e-01,  1.2600e+00, -6.8534e-01, -2.8664e+00, -

In [44]:
a.view(-1, 12).unsqueeze(1).repeat(1, 3, 1).view(2, 9, 12)

tensor([[[-6.6831e-02, -5.2485e-01,  6.1045e-01, -7.6859e-02,  4.9431e-01,
           1.8986e-01, -1.8368e+00, -1.3222e+00,  8.7111e-01,  4.3258e-01,
          -3.2533e-01,  8.9563e-01],
         [-6.6831e-02, -5.2485e-01,  6.1045e-01, -7.6859e-02,  4.9431e-01,
           1.8986e-01, -1.8368e+00, -1.3222e+00,  8.7111e-01,  4.3258e-01,
          -3.2533e-01,  8.9563e-01],
         [-6.6831e-02, -5.2485e-01,  6.1045e-01, -7.6859e-02,  4.9431e-01,
           1.8986e-01, -1.8368e+00, -1.3222e+00,  8.7111e-01,  4.3258e-01,
          -3.2533e-01,  8.9563e-01],
         [ 7.7752e-04,  1.3285e+00, -7.5241e-02, -1.2557e-02,  8.4139e-01,
           3.9887e-04,  2.2646e-01, -7.8450e-01,  5.8338e-01, -1.7438e+00,
           1.2119e+00,  1.0964e+00],
         [ 7.7752e-04,  1.3285e+00, -7.5241e-02, -1.2557e-02,  8.4139e-01,
           3.9887e-04,  2.2646e-01, -7.8450e-01,  5.8338e-01, -1.7438e+00,
           1.2119e+00,  1.0964e+00],
         [ 7.7752e-04,  1.3285e+00, -7.5241e-02, -1.2557e-02,  8.

In [27]:
import torch
mask = (torch.eye(3)[0]!=1).bool()
mask = mask.repeat(8, 1).unsqueeze(2)
mask.shape

torch.Size([8, 3, 1])

In [28]:
mask

tensor([[[False],
         [ True],
         [ True]],

        [[False],
         [ True],
         [ True]],

        [[False],
         [ True],
         [ True]],

        [[False],
         [ True],
         [ True]],

        [[False],
         [ True],
         [ True]],

        [[False],
         [ True],
         [ True]],

        [[False],
         [ True],
         [ True]],

        [[False],
         [ True],
         [ True]]])

In [29]:
emb = torch.randn((8, 3, 70))


In [32]:
emb[:,1:,:].shape

torch.Size([8, 2, 70])

In [36]:
indices = torch.tensor([0, 2])
torch.index_select(emb, 1, indices).shape


torch.Size([8, 2, 70])

In [11]:
ws(doc[0][0])

['<',
 '1',
 '>',
 '好',
 '。',
 '<',
 '2',
 '>',
 '阿',
 '假如',
 '你',
 '急',
 '的',
 '話',
 '，',
 '<',
 '2',
 '>',
 '你',
 '就',
 '十二',
 '天',
 '左右',
 '齁',
 '，',
 '<',
 '2',
 '>',
 '你',
 '就',
 'line',
 '一下',
 '那',
 '個',
 '⋯⋯',
 '<',
 '1',
 '>',
 '我',
 '沒有',
 '很',
 '急',
 '。',
 '<',
 '2>沒',
 '有',
 '很',
 '急喔',
 '？',
 '<',
 '1',
 '>',
 '對',
 '阿～<2',
 '>',
 '喔',
 '，',
 '<',
 '2',
 '>',
 '我',
 '⋯⋯',
 '<',
 '2',
 '>',
 '我',
 '⋯⋯',
 '<',
 '2',
 '>',
 '我',
 '，',
 '<',
 '2',
 '>',
 '我',
 '相信',
 '是',
 '應該ok',
 '啦',
 '。',
 '<',
 '1',
 '>',
 '好',
 '。',
 '<',
 '2',
 '>',
 '阿',
 '其他',
 '拉肚子',
 '都',
 '，',
 '<',
 '2',
 '>',
 '部份',
 '都',
 'ok',
 '了',
 '嗎',
 '？',
 '<',
 '1',
 '>',
 '都',
 'ok',
 '了',
 '，',
 '<',
 '1',
 '>',
 '對',
 '。',
 '<',
 '2',
 '>',
 '阿',
 '你',
 '四環素',
 '那',
 '個',
 '綠色',
 '的',
 '有',
 '吃完',
 '了',
 '？',
 '<',
 '1',
 '>',
 '後',
 '來',
 '⋯⋯',
 '<',
 '2',
 '>然',
 '後',
 '呢',
 '？',
 '<',
 '1',
 '>',
 '後',
 '來',
 '突然',
 '找到',
 '那',
 '個',
 '⋯⋯',
 '<',
 '1',
 '>',
 '那',
 '個',
 '⋯⋯',
 '<',
 '2',
 '>',
 '是

In [ ]:
frag_len = [ len(frag) for frag_doc in doc for frag in frag_doc]
max(frag_len), min(frag_len)

In [ ]:
plt.title('Fragment len')
plt.hist(frag_len)
plt.show()

In [ ]:
allfragment_len = [sum([len(e) for e in ele]) for ele in doc]
plt.hist(allfragment_len)
plt.show()


In [6]:
import torch
prob = torch.randn((2,3,2))
prob

tensor([[[-1.2928, -0.5293],
         [-1.3508, -0.0625],
         [ 1.0319,  0.2355]],

        [[-1.1853,  0.8645],
         [-0.0995, -1.1394],
         [ 0.1403,  0.4403]]])

In [7]:
torch.max(prob, dim=1).indices[:, 1]

tensor([2, 0])

In [ ]:
def cat_sents(idx, end):
    indices = [idx]
    head = tail = idx
    dir = 0
    while len(indices) != 16:
        print(head, tail)
        if tail+1< end and dir==0: 
            tail+=1
            indices.append(tail)
        elif head-1>=0 and dir==1:
            head-=1   
            indices.append(head)
        dir=not dir
    return indices

In [ ]:
cat_sents(48, 50)

In [ ]:
import difflib

In [ ]:
difflib.SequenceMatcher(None, '123', '56161').quick_ratio()

In [ ]:
import numpy as np
a = np.array([
    [3, 40, 20,],
    [1, 56, 21],
    [441, 560, 28],
    [11, 5, 2],
])


In [ ]:
ind = np.argpartition(a, -3, axis=0)[-3:]
ind


In [ ]:
ind[:, 0]

In [ ]:
ind[np.argsort(a[ind])]


In [ ]:
import torch 

In [ ]:
a = torch.rand((1,2,3))
b = torch.rand((1,3,3))
a,b

In [ ]:
torch.cat((a, b), dim=1)

In [ ]:
with open('./data/stop_word.txt') as f:
    text = f.read()
    text = text.split('\n')

In [ ]:
[1,2] + [2,3]

In [ ]:
tags = jieba.analyse.extract_tags('醫師：我們6月30號抽血，免疫細胞指數還不錯這樣子，然後病毒量也是OK，阿血糖，糖化血色素7.2，還不錯，所以控制的還不錯，所以表示這段時間身體狀況應該還好。民眾：因為我有重訓和訓練……醫師：低密度膽固醇101是正常，是可以的，然後因為有一點點尿酸稍微高一點點，但是還不需要吃藥，就是飲食稍微注意一下就好，會造成尿酸高一點的食物稍微控制一下就好。民眾：我不知道哪些。醫師：不')
tags

In [1]:
import spacy
from spacy.lang.zh import Chinese
from spacy.language import Language

text = "民眾：沒關係啦，看你怎麼看都可以。醫師：沒有啦要先經過你同意啦。民眾：啊抽血結果怎麼樣？醫師：嗯9月2號抽血，糖化血色素9．7。民眾：可是我比較重了欸。醫師：比較重了。民眾：56了欸。醫師：假如血糖高會應該會越來越輕嘛，對嗎？民眾：嘿啊，其實我現在已經56了欸。醫師：啊其他膽固醇這些都正常，肝功能、腎功能。民眾：啊9．6喔？醫師：9．8嗯。民眾：比上次還要高還是？醫師：上次9．6，也是跟上次差不多。民眾：差不多啦。醫師：啊酒沒有喝少一點？民眾：一樣。醫師：一樣喔？你知道喝酒也會血也是有熱量的欸。民眾：我知道啊。醫師：你知道齁。民眾：喝酒也是有糖分啊。醫師：對啊，啊你尿尿沒有問題吧？尿尿沒有蛋白尿？民眾：沒有。醫師：好齁。民眾：那就先這樣就好了。醫師：這樣就好了。民眾：啊眼睛甚麼時候要看？這我是看東西的時候前面會亮亮的嗎？是不是？醫師：會霧霧的嗎？民眾：眼球正中央會發光嘛。醫師：2019我看看，發光你有你會這樣喔？欸年底的時候要追蹤。民眾：好像。醫師：嘿，年底。民眾：沒有常常就好像早上起來之後。醫師：他有上次講、你3月的時候有做嘛。民眾：嗯。醫師：啊7個月的所以是10月，10月底的時候要追蹤，對啊。民眾：嗯啊狀況是怎麼樣。醫師：嗯有輕微的有輕微的一些糖尿病的病變，輕微，嘿，所以要注意啊血糖還有酒要喝少一點喔。民眾：喔。醫師：不然會青光眼。民眾：那個是我的眼球？醫師：就是你的眼底，就是這個這是眼底裡面的血管這樣子。民眾：喔，而且眼睛閉起來的時候眼睛正中央還是發亮的，不是黑黑的欸，他有發亮，可是不，沒有常常。醫師：沒有常常啦，是太亮了，還是你看螢幕？民眾：就⋯⋯醫師：看手機？民眾：類似一點綠色的這樣。醫師：哦～民眾：啊是在眼球正中央，啊是閉上眼睛會這樣。醫師：嗯。民眾：閉上眼睛應該是全黑嘛。醫師：全黑嗯。民眾：啊會覺得這裡怎麼好像。醫師：會有殘影啦齁。民眾：嘿嘿嘿嘿。醫師：不過看起來應該還好。民眾：那沒關係。醫師：沒關係我們快要到，我們下一次可能就要到。民眾：到眼底。醫師：要再做眼底了欸。民眾：沒關係我家查那個電腦。醫師：好好。民眾：看那個狀況是甚麼。醫師：啊血糖跟針就這樣子這樣好不好？民眾：好好好好。醫師：啊，那個。民眾：安眠藥一定要。醫師：安眠藥一定要齁。民眾：習慣了。醫師：習慣了，好，那我下次回診的時候我就會開檢查眼睛的單子。民眾：好。醫師：那假如你那個有惡化你就是先去看眼科。民眾：我是不知道甚麼情況。醫師：模糊的啊，看東西啊。民眾：模糊的是因為我，我有近視嘛。醫師：近視。民眾：我帶隱形眼鏡我字就看不到了，拿下就看的到了。醫師：嘿，好喔。民眾：我也不知道是甚麼情況。醫師：好喔。民眾：要是我戴眼鏡就一直都很正常。醫師：很正常。民眾：戴隱形眼鏡就感覺不太正常。醫師：不太正常。民眾：沒關係我參考醫生的指示。醫師：試試看。民眾：好。"

In [2]:
@Language.component("set_custom_boundaries")
def set_custom_boundaries(doc, on_special_token=True):
    
    position = ['民眾', '個管師', '醫師', '女醫師', '護理師', '家屬', '藥師', ]
    position = [ role + ele + '：' for role in position for ele in ['', 'A', 'B', '1', '2']]

    for token in doc[:-1]:
        if token.text in position:
            doc[token.i].is_sent_start = True
        elif on_special_token and token.i>0 and doc[token.i-1].text in ['，', '？', '。', ]:
            doc[token.i].is_sent_start = True
        else:
            doc[token.i].is_sent_start = False
    return doc


nlp = spacy.load("zh_core_web_sm")
nlp = Chinese()
nlp = Chinese.from_config({"nlp": {"tokenizer":{"segmenter": "pkuseg"}}})
nlp.tokenizer.initialize(pkuseg_model="mixed", pkuseg_user_dict='./data/pkuseg_user_dict.txt')
nlp.add_pipe("sentencizer")
nlp.add_pipe("set_custom_boundaries")
doc = nlp(text)


In [11]:
role = [
    ['民眾'],
    ['醫師'],
    ['家屬'],
    ['個管師'],
    ['護理師', '女醫師', '藥師']
]
role_map = {
    k:i for i, sublist in enumerate(role)  for k in sublist
}
role_map = {k+postfix:v for k,v in role_map.items() for postfix in ['', 'A', 'B', '1', '2' ] }
sentences = [e.text for e in doc.sents  ]

In [12]:
role_id = []
roid = 0
for si, s in enumerate(sentences):
    pos = s.find('：')
    role = s[:pos]

    if role in role_map.keys():
        roid = role_map[role]
        sentences[si] = f'<{roid}>'+ s[pos+1:]
    else:
        sentences[si] = f'<{roid}>'+ s

In [13]:
sentences

['<0>沒關係啦，',
 '<0>看你怎麼看都可以。',
 '<1>沒有啦要先經過你同意啦。',
 '<0>啊抽血結果怎麼樣？',
 '<1>嗯9月2號抽血，',
 '<1>糖化血色素9．7。',
 '<0>可是我比較重了欸。',
 '<1>比較重了。',
 '<0>56了欸。',
 '<1>假如血糖高會應該會越來越輕嘛，',
 '<1>對嗎？',
 '<0>嘿啊，',
 '<0>其實我現在已經56了欸。',
 '<1>啊其他膽固醇這些都正常，',
 '<1>肝功能、腎功能。',
 '<0>啊9．6喔？',
 '<1>9．8嗯。',
 '<0>比上次還要高還是？',
 '<1>上次9．6，',
 '<1>也是跟上次差不多。',
 '<0>差不多啦。',
 '<1>啊酒沒有喝少一點？',
 '<0>一樣。',
 '<1>一樣喔？',
 '<1>你知道喝酒也會血也是有熱量的欸。',
 '<0>我知道啊。',
 '<1>你知道齁。',
 '<0>喝酒也是有糖分啊。',
 '<1>對啊，',
 '<1>啊你尿尿沒有問題吧？',
 '<1>尿尿沒有蛋白尿？',
 '<0>沒有。',
 '<1>好齁。',
 '<0>那就先這樣就好了。',
 '<1>這樣就好了。',
 '<0>啊眼睛甚麼時候要看？',
 '<0>這我是看東西的時候前面會亮亮的嗎？',
 '<0>是不是？',
 '<1>會霧霧的嗎？',
 '<0>眼球正中央會發光嘛。',
 '<1>2019我看看，',
 '<1>發光你有你會這樣喔？',
 '<1>欸年底的時候要追蹤。',
 '<0>好像。',
 '<1>嘿，',
 '<1>年底。',
 '<0>沒有常常就好像早上起來之後。',
 '<1>他有上次講、你3月的時候有做嘛。',
 '<0>嗯。',
 '<1>啊7個月的所以是10月，',
 '<1>10月底的時候要追蹤，',
 '<1>對啊。',
 '<0>嗯啊狀況是怎麼樣。',
 '<1>嗯有輕微的有輕微的一些糖尿病的病變，',
 '<1>輕微，',
 '<1>嘿，',
 '<1>所以要注意啊血糖還有酒要喝少一點喔。',
 '<0>喔。',
 '<1>不然會青光眼。',
 '<0>那個是我的眼球？',
 '<1>就是你的眼底，',
 '<1>就是這個這是眼底裡面的血管這樣子。',
 '<0>喔，',
 '<0>

In [6]:
next(doc.sents).text.find('：')

2

In [20]:
role = [
    ['民眾',],
    ['家屬',],
    ['個管師',],
    ['醫師', '女醫師'],
    ['護理師', '藥師', ],
]
all_role = [
    [r+postfix for r in sublist for postfix in ['' ,'A', 'B', '1', '2']] 
    for sublist in role 
]
role_map = {
    k:i for i, sublist in enumerate(all_role) for k in  sublist
}

In [21]:
role_map

{'民眾': 0,
 '民眾A': 0,
 '民眾B': 0,
 '民眾1': 0,
 '民眾2': 0,
 '家屬': 1,
 '家屬A': 1,
 '家屬B': 1,
 '家屬1': 1,
 '家屬2': 1,
 '個管師': 2,
 '個管師A': 2,
 '個管師B': 2,
 '個管師1': 2,
 '個管師2': 2,
 '醫師': 3,
 '醫師A': 3,
 '醫師B': 3,
 '醫師1': 3,
 '醫師2': 3,
 '女醫師': 4,
 '女醫師A': 4,
 '女醫師B': 4,
 '女醫師1': 4,
 '女醫師2': 4,
 '護理師': 4,
 '護理師A': 4,
 '護理師B': 4,
 '護理師1': 4,
 '護理師2': 4,
 '藥師': 4,
 '藥師A': 4,
 '藥師B': 4,
 '藥師1': 4,
 '藥師2': 4}

In [11]:
[sen.text for sen in doc.sents]

['民眾：沒關係啦，',
 '看你怎麼看都可以。',
 '醫師：沒有啦要先經過你同意啦。',
 '民眾：啊抽血結果怎麼樣？',
 '醫師：嗯9月2號抽血，',
 '糖化血色素9．7。',
 '民眾：可是我比較重了欸。',
 '醫師：比較重了。',
 '民眾：56了欸。',
 '醫師：假如血糖高會應該會越來越輕嘛，',
 '對嗎？',
 '民眾：嘿啊，',
 '其實我現在已經56了欸。',
 '醫師：啊其他膽固醇這些都正常，',
 '肝功能、腎功能。',
 '民眾：啊9．6喔？',
 '醫師：9．8嗯。',
 '民眾：比上次還要高還是？',
 '醫師：上次9．6，',
 '也是跟上次差不多。',
 '民眾：差不多啦。',
 '醫師：啊酒沒有喝少一點？',
 '民眾：一樣。',
 '醫師：一樣喔？',
 '你知道喝酒也會血也是有熱量的欸。',
 '民眾：我知道啊。',
 '醫師：你知道齁。',
 '民眾：喝酒也是有糖分啊。',
 '醫師：對啊，',
 '啊你尿尿沒有問題吧？',
 '尿尿沒有蛋白尿？',
 '民眾：沒有。',
 '醫師：好齁。',
 '民眾：那就先這樣就好了。',
 '醫師：這樣就好了。',
 '民眾：啊眼睛甚麼時候要看？',
 '這我是看東西的時候前面會亮亮的嗎？',
 '是不是？',
 '醫師：會霧霧的嗎？',
 '民眾：眼球正中央會發光嘛。',
 '醫師：2019我看看，',
 '發光你有你會這樣喔？',
 '欸年底的時候要追蹤。',
 '民眾：好像。',
 '醫師：嘿，',
 '年底。',
 '民眾：沒有常常就好像早上起來之後。',
 '醫師：他有上次講、你3月的時候有做嘛。',
 '民眾：嗯。',
 '醫師：啊7個月的所以是10月，',
 '10月底的時候要追蹤，',
 '對啊。',
 '民眾：嗯啊狀況是怎麼樣。',
 '醫師：嗯有輕微的有輕微的一些糖尿病的病變，',
 '輕微，',
 '嘿，',
 '所以要注意啊血糖還有酒要喝少一點喔。',
 '民眾：喔。',
 '醫師：不然會青光眼。',
 '民眾：那個是我的眼球？',
 '醫師：就是你的眼底，',
 '就是這個這是眼底裡面的血管這樣子。',
 '民眾：喔，',
 '而且眼睛閉起來的時候眼睛正中央還是發亮的，',
 '不是黑黑的欸，',
 '他有發亮，',
 '可是不，',
 '沒有常常。'

In [ ]:
a = torch.tensor([
    [
        [1,2,3],
        [0,0,0],
        [3,4,3]
    ],
    [
        [1,2,3],
        [1,2,3],
        [3,4,3]
    ],
], dtype=torch.float)
b = torch.tensor([
    [
        [1,2,3],
        [3,4,3]
    ],
    [
        [1,2,3],
        [3,4,3]
    ],
], dtype=torch.float)
cosine_sim()(a, b)

In [ ]:
cosine_sim()(a, b)

In [ ]:
torch.max(cosine_sim()(a, b), 1)

In [ ]:
# output = torch.randn(2, 4, 768)
# choi_output = torch.randn(2, 3, 768)
cosine_sim(None)(a, b)

In [ ]:
vec1=a
vec2=b

vec2 = torch.transpose(vec2, 1, 2)
norm1 = torch.linalg.norm(vec1, dim=2)
norm2 = torch.linalg.norm(vec2, dim=1)   
norm1 = norm1.unsqueeze(-1).expand(2, vec1.size(1), vec1.size(2))
norm2 = norm2.unsqueeze(2).expand(2, vec2.size(2), vec2.size(1))
norm2 = torch.transpose(norm2, 1, 2)
eledot = torch.matmul(torch.div(vec1, norm1), torch.div(vec2, norm2))

# print(torch.mul(norm1.transpose(0, 1), norm2))
# cos_sim = torch.div(eledot ,torch.matmul(norm1.transpose(0, 1), norm2))
eledot

In [ ]:
norm2 = norm2.unsqueeze(2).expand(2, vec2.size(2), vec2.size(1))
norm2 = torch.transpose(norm2, 1, 2)

In [ ]:
' rock '

In [1]:
from loader import QA_Dataset
from transformers import AutoTokenizer
config = 'hfl/chinese-xlnet-base'
tokenizer = AutoTokenizer.from_pretrained(config)


In [4]:
example = QA_Dataset(tokenizer, './data/train_fold1.json').__getitem__(1)
example['input_ids'].shape

民眾：對。<sep>但是基本上假如說從來跟那個人沒有任何性行為過的話，這部份就會選擇戴。個管師：選擇戴。OKOK。所以你基本上對於不信任的還是會戴，但是你覺得信任的你就不會戴？民眾：對。個管師：嗯好。可是這相對來說對你來說也是有風險的誒。<sep>他有在吃PrEP。民眾：對。個管師：然後現在因為你也沒有固炮，所以約的話就是你覺得看起來信不信任，如果比較信任的話你就會不戴。民眾：呃……不戴反而比較少，基本上，反正就是那些，', '民眾的腳下列何種不是目前的狀況?看到下面都透明，就是都可以看到比較深，就是皮膚變得很薄'), ('民眾：偶爾。個管師：偶爾內射？民眾：對。個管師：好喔那會不會因為你吃PrEP會比較不用，不會擔心？民眾：會，對啊我就比較不擔心。個管師：真的喔。民眾：我每日吃的。個管師：啊你知道怎麼吃嗎？你是吃任務型對不對。民眾：沒有我吃每日型。個管師：你現在吃每日……民眾：我一樣吃是吃每日型。個管師：那你這樣藥怎麼會夠？民眾：就沒有給哥哥啊。<sep>目前啦，目前還沒有說幾個名額民眾：嗯。個管師：但是目前我們今年有在排候補了，如果他要的話就幫你排候補。民眾：好。個管師：對，然後這樣子其實兩個都有吃，因為你們兩個幾乎都是無套嘛。民眾，嗯。個管師：所以雖然……雖然彼此相信就是不會各自約，可是有時候還是要相信自己，要保護自己一下。民眾：嗯好。個管師：對啊，所以因為在之前階段的狀況就是很多時候大家會知道吃PrEP可以預防ＨＩＶ，然後就會開始無套，', '民眾的腳下列何種不是目前的狀況?好像有點疹子')]
[('個管師：那有固定伴侶嗎？民眾：沒有。個管師：你一直以來都沒有固定伴侶欸？民眾：蛤？什麼？個管師：你從一開始就沒有固定伴侶。民眾：你說來這裡之後？個管師：對。民眾：你說有固定伴侶是指固炮類的還是？個管師：固炮是固炮，固伴是固伴。民眾：沒有。個管師：固炮、固伴跟約炮是不一樣的。民眾：OK。個管師：對，就是固伴就是一般問你有沒有男朋友。民眾：沒有。<sep>他在紐約醫院吃PrEP？民眾：他在紐約醫院，他是去紐約醫院看的。個管師：吃PrEP？民眾：對。個管師：OKOK，好，所以你會之前的一個固炮，所以你現在都不會跟他了？民眾：對不會，他也有固定的伴侶了。個管師：所以他還沒有固定伴侶之前，你們是維持固炮關係？民眾：對。個管師：然後他現在有伴侶了，所以就沒有固炮了？民眾：對

torch.Size([3, 365])

In [5]:
tokenizer.decode(example['input_ids'][2])

'<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad> 民眾:偶爾。個管師:偶爾內射?民眾:對。個管師:好喔那會不會因為你吃PrEP會比較不用,不會擔心?民眾:會,對啊我就比較不擔心。個管師:真的喔。民眾:我每日吃的。個管師:啊你知道怎麼吃嗎?你是吃任務型對不對。民眾:沒有我吃每日型。個管師:你現在吃每日......民眾:我一樣吃是吃每日型。個管師:那你這樣藥怎麼會夠?民眾:就沒有給哥哥啊。<sep> 目前啦,目前還沒有說幾個名額民眾:嗯。個管師:但是目前我們今年有在排候補了,如果他要的話就幫你排候補。民眾:好。個管師:對,然後這樣子其實兩個都有吃,因為你們兩個幾乎都是無套嘛。民眾,嗯。個管師:所以雖然......雖然彼此相信就是不會各自約,可是有時候還是要相信自己,要保護自己一下。民眾:嗯好。個管師:對啊,所以因為在之前階段的狀況就是很多時候大家會知道吃PrEP可以預防HIV,然後就會開始無套,<sep> 下列關於民眾敘述何者錯誤?想要改任務型<sep><cls>'

In [ ]:
tokenizer.decode(ins['q_input_ids'][0])

In [ ]:
import pandas as pd
from loader import *
import matplotlib.pyplot as plt
from transformers import AutoTokenizer


config = 'hfl/chinese-xlnet-base'
tokenizer = AutoTokenizer.from_pretrained(config)
doc, q, cho, ans = json_parser()

In [ ]:
def find_entity(strs, ent, dir='f'):
    try:
        idx = strs.index(ent)
        idx = idx-1 if dir=='f' else idx+1
        return strs[idx]
    except:
        return 0
def query_propress(query):
    valid_ent = ['民眾', '醫師', '個管師', '家屬']
    rules=[ 
        {'p':'關於','dir':'b'}, {'p':'建議','dir':'f'},
        {'p':'是', 'dir':'b'}, {'p':'不是', 'dir':'b'},
        {'p':'請問', 'dir':'b'}
    ]
    processed_q = []
    for q in query:
        tokens = jieba.lcut(q)
        # print(tokens)
        res = ''
        for ele in rules:
            res = find_entity(tokens, ele['p'], dir=ele['dir'])  

            if res in valid_ent: break
        # Clearing invalid ent
        if not res in valid_ent:
            res= tokens[0] if tokens[0] in valid_ent else ''
            
        processed_q.append(res)
    return processed_q


In [ ]:
propressed_query = query_propress(q)
list(zip(q, propressed_query))

In [ ]:
pipe =  doc_preprocessing(config)
d = pipe(doc, q)

# ori_len = [len(window) for frag in d for window in frag['input_ids']]
# plt.hist(ori_len, color = 'black', cumulative = False)
# plt.show()

In [ ]:
tokenizer.decode(d[0]['q_input_ids'][0])

In [ ]:
plt.hist(strQ2B(ans))
plt.show()


## LOADER

In [ ]:
from torch.utils.data import DataLoader
from loader import QA_Dataset
from torch.nn.utils.rnn import pad_sequence
import torch

config = 'hfl/chinese-xlnet-base'
lr = 1e-3

In [ ]:
import  torch.nn.functional as F
from torch.nn.utils.rnn import pad_sequence
a = torch.ones(25, 300)
b = torch.ones(22, 300)
c = torch.ones(15, 300)
pad_sequence([a, b, c], batch_first=True,).shape

In [ ]:
def fragment_pad(*dcts):
    combined_dict = {}
    for k in set(dcts[0]):
        if not k=='label' and not k=='choice':
            print(k, [d[k].shape for d in dcts])
            combined_dict.update({
                k:pad_sequence([d[k].squeeze(0) for d in dcts], batch_first=True)
            })
        if k=='label':
             combined_dict.update({
                'label':torch.stack([d['label'] for d in dcts]) 
             })
    return combined_dict

def collate_fn(batch):
    batched_dict = fragment_pad(*batch)
    return batched_dict

train_ds = QA_Dataset(config, './data/Train_qa_ans.json')
train_loader = DataLoader(
    train_ds, 
    batch_size=4, 
    num_workers=1, 
    shuffle=True, 
    collate_fn=collate_fn
)
train_loader.__iter__().__next__()
# model = QA_Model(config, lr=lr)

In [ ]:
from loader import QA_Dataset

In [ ]:
from transformers import XLNetTokenizer, XLNetModel
import torch

config = 'hfl/chinese-xlnet-base'
tokenizer = XLNetTokenizer.from_pretrained(config)
tokenizer.add_special_tokens({'additional_special_tokens':['<q>']})
model = XLNetModel.from_pretrained(config)
model.resize_token_embeddings(len(tokenizer))

In [ ]:
tokenizer([
    ('預計的性行為', '預計的性行為'),
    ('預預預預預預', '預預預預預預'),

])['input_ids'][0]

In [ ]:
tokenizer.decode(19)

In [2]:
import jieba
from loader import *

doc, q, cho, ans = json_parser('./data/train_fold0.json')

jieba.load_userdict('./data/dict.txt') 

for c in q:
    print(jieba.lcut(c))

['下列', '敘述', '何者', '有誤', '?']
['請問', '民眾', '會', '是', '怎樣', '的', '狀況', '下會', '沒', '戴', '保險套', '？']
['下列', '何者', '是', '民眾', '今天', '要', '做', '的', '檢查', '？']
['醫師', '從', '哪判斷', '民眾', '是', '恙蟲病', '？']
['民眾', '平', '常常', '吃', '的', '東西', '下列', '何者', '正確', '？']
['請問', '民眾', '先前', '有', '做', '過何', '項', '治療', '？']
['下列', '何者', '不是', '民眾', '提早', '來', '打', '疫苗', '的', '原因', '?']
['下列', '何者', '是', '民眾', '持續', '做', '的', '治療', '？']
['下列', '敘述', '何者', '正確', '?']
['下列', '敘述', '何者', '錯誤', '？']
['下列', '哪個', '不是', '民眾', '的', '症狀', '?']
['請問', '民眾', '打針', '打', '多久', '？']
['醫師', '建議', '民眾', '把', '下列', '何者', '藥物', '停掉', '？']
['下列', '何者', '不是', '民眾', '的', '身體', '狀況', '？']
['何者', '是', '民眾', '的', '症狀', '?']
['請問', '下列', '何者', '不是', '醫師', '建議', '民眾', '打', '的', '疫苗', '？']
['請問', '民眾', '哪一項', '指數', '有', '慢慢', '在', '繼續', '往', '下降', '？']
['關於', '民眾', '的', '身體', '狀況', '下列', '何者', '錯誤', '？']
['請問', '醫師', '建議', '民眾', '追', '蹤', '下列', '何項', '指數', '的', '抗體', '？']
['下列', '關於', '民眾', '的', '敘述', '何者', '錯誤', '?']
['請問', '藥要', '連

In [ ]:
for ele in ids[0]:
    print(    tokenizer.decode(ele))


In [ ]:
tokenizer.decode(ids[1])

## Model

In [ ]:
h = model(**encoding).last_hidden_state

In [ ]:
from transformers.modeling_utils import SequenceSummary


In [ ]:
s = SequenceSummary(config)
getattr(config, 'summary_type', 'last')

In [ ]:
import torch

a = torch.randn(2,3,7)
a


In [ ]:
torch.cat([a,a,a], dim=2).shape

In [ ]:
index = torch.tensor([
    [ 1,2,1 ],
    [ 1,2,2 ],
])

max_val = [a.index_select(1, ele[1])[ele[0]] for ele in enumerate(index)]
# a.index_select(1, index)
max_val

In [ ]:
 torch.cat(max_val).view(2,-1, 7)

In [ ]:
# MEM 

In [ ]:
from transformers import AutoModel, AutoConfig

model_name = 'hfl/chinese-xlnet-base'

config = AutoConfig.from_pretrained(
        model_name,
        n_layer=3,
)
query_encoder = AutoModel.from_pretrained(
        model_name,
        config=config,
)



In [47]:
q = torch.randn((2,50,768))
logits = torch.randn((5,3,2))
c_mask = torch.empty((2,300)).random_(2)
logits

tensor([[[ 0.0666, -0.3275],
         [ 0.6962,  0.3852],
         [ 0.7146,  1.1341]],

        [[ 1.0068,  1.7619],
         [ 0.8368, -0.3765],
         [ 0.3889, -1.3195]],

        [[-1.1517,  1.3820],
         [ 1.5773, -1.3607],
         [ 0.0523,  0.0858]],

        [[ 0.9616,  0.3363],
         [ 0.4100, -0.9522],
         [-1.6811, -0.6102]],

        [[-0.7779,  0.2164],
         [-0.1804,  0.9739],
         [-0.1297, -1.6887]]])

In [49]:

logits = logits.view(-1, 3, 2)
pred = torch.max(logits, dim=1).indices
# print(pred.shape)
pred = pred[:, 1]
pred


tensor([2, 0, 0, 0, 1])

In [43]:
att(q, c, c_mask, c_mask).shape

torch.Size([2, 50, 768])